import { BcryptPasswordHasher } from "./bcrypt-password-hasher";

describe("BcryptPasswordHasher", () => {
  const hasher = new BcryptPasswordHasher();

  it("hashes a password and verifies it via compare()", async () => {
    const hash = await hasher.hash("correct-horse-battery");
    expect(hash).not.toEqual("correct-horse-battery");
    await expect(hasher.compare("correct-horse-battery", hash)).resolves.toBe(true);
  });

  it("rejects an incorrect password against a valid hash", async () => {
    const hash = await hasher.hash("correct-horse-battery");
    await expect(hasher.compare("wrong-password", hash)).resolves.toBe(false);
  });

  it("produces a $2a$/$2b$ modular crypt hash at cost factor 12 (OWASP推奨値)", async () => {
    const hash = await hasher.hash("correct-horse-battery");
    expect(hash).toMatch(/^\$2[aby]\$12\$/);
  });

  it("verifies a hash generated by the native `bcrypt` library (real cross-implementation vector, not bcryptjs), confirming existing users' stored password hashes remain valid after the bcrypt→bcryptjs infrastructure swap", async () => {
    // 実際にPython bcrypt（native実装）で生成した 'CorrectHorseBatteryStaple' のcost=12ハッシュ。
    // bcryptjsへの切替後も既存ユーザーのパスワードハッシュがそのまま検証できることを保証する。
    const realBcryptHash = "$2b$12$ssVGlawbUCzwONM.qF/qduFUOfzJ9B9mq9uR6/UU2mkc0c7zJnL7O";
    await expect(hasher.compare("CorrectHorseBatteryStaple", realBcryptHash)).resolves.toBe(true);
  });
});
